import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Footer } from '@/components/footer/footer'
import Container from '@/components/container/container'
import Header from '@/components/header/header'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" 
              content="width=device-width,
              height=device-height,
              initial-scale=1.0,"
        />
      </head>
      <body>
      {children}
       <div>
          <Header/>
           <main className='bg-page-gradient pt-[var(--navigation-height)]'>{children}</main>        
          <Footer/>
   
          </div>
        </body>
    </html>
  )
}
